repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Remplace par la dernière version de mypy
    hooks:
      - id: mypy
        args: ["back/"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3  # Remplace par la dernière version de ruff
    hooks:
      - id: ruff
      - id: ruff-format 

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]
        args: ["back/tests"]
