# mypy: ignore-errors
"""Reduction des champ à la table Card

Revision ID: c4d5420fd6be
Revises: b64afbcffba4
Create Date: 2025-04-05 18:01:06.551442

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c4d5420fd6be"
down_revision: Union[str, None] = "b64afbcffba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "cube_card_association", "cards", ["card.id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cube_card_association", type_="foreignkey")
    # ### end Alembic commands ###
